language: php

php:
    - 5.3
    - 5.4
    - 5.5

env:
    - HHVM=true
    - HHVM=false

before_install:
    # Define the IS_HHVM_JOB variable
    - if [[ $HHVM == true && `phpenv global` == "5.5" ]] ; then IS_HHVM_JOB=true ; else IS_HHVM_JOB=false ; fi
    # Define the IS_PHP_JOB variable
    - if [[ $HHVM == false ]] ; then IS_PHP_JOB=true ; else IS_PHP_JOB=false ; fi
    # Install HHVM if needed
    - if [[ $IS_HHVM_JOB == true ]] ; then sudo .bin/install_hhvm; fi

before_script:
    - curl -s http://getcomposer.org/installer | php
    - php composer.phar install --dev

script:
    - if [[ $IS_PHP_JOB == true ]]  ; then ./vendor/bin/phpunit --coverage-text ; fi
    - if [[ $IS_HHVM_JOB == true ]] ; then hhvm -f vendor/bin/phpunit ; fi
